#!/bin/bash

touch /etc/xdg/autostart/AutoLRPT.desktop
echo "" > /etc/xdg/autostart/AutoLRPT.desktop
echo "[Desktop Entry]" >> /etc/xdg/autostart/AutoLRPT.desktop
echo "Name=AutoLRPT" >> /etc/xdg/autostart/AutoLRPT.desktop
echo "Type=Application" >> /etc/xdg/autostart/AutoLRPT.desktop
echo "Exec=bash $HOME/AutoLRPT/scheduler" >> /etc/xdg/autostart/AutoLRPT.desktop
echo "Terminal=false" >>  /etc/xdg/autostart/AutoLRPT.desktop

nano /etc/xdg/autostart/AutoLRPT.desktop
