#!/bin/bash

## Image reception in the evening
# In the evening the lrpt images tend to become quite dark and not that colorful as they are in the morning.
# There are also not that many details visible in the images anymore.
# If you want to disable the image reception in the evenings, you can change the value from 1 to 0.
evening_rec=1;

# Setting the color channels in ~/mlrpt/default.cfg
wget http://happysat.nl/Meteor/html/Meteor_Status.html
apid66=`sed '182q;d' Meteor_Status.html`
apid68=`sed '191q;d' Meteor_Status.html`

if [[ $apid66 == *"On"* ]] ; then
sed -i '123s/.*/66/' ~/mlrpt/default.cfg
fi

if [[ $apid68 == *"On"* ]] ; then
sed -i '123s/.*/68/' ~/mlrpt/default.cfg
fi

rm ~/AutoLRPT/Meteor_Status.html


# Get time of the upcoming pass from predict
passtime=`predict '-p' METEOR-M2 | grep -o -m1 [0-2][0-9]:[0-5][0-9]:[0-5][0-9]`

passhour=`cut -c 1-2 <<< $passtime`
passmin=`cut -c 4-5 <<< $passtime`
passsec=`cut -c 7-8 <<< $passtime`

if [ $passhour -lt 10 ]; then
passhour=`echo $passhour | cut -c 2-2`
fi
# Convert from UTC to local time
tzoffset=`date +%z | cut -c 1-3`
passhour=$(($passhour + $tzoffset))

# If the pass starts later than half of a minute,
# it will be scheduled one minute later for optimal
# reception time.
if [ $passsec -ge 30 ]; then
passmin=$(expr $passmin + 1)
fi

if [ $passmin -lt 10 ] && [ $passsec -ge 30 ]; then
passmin=0$passmin
fi

if [ $passmin -eq 60 ]; then
passhour=$(expr $passhour + 1)
passmin="00"
fi

if [ $passhour -ge 24 ]; then
passhour=$(expr $passhour % 24)
fi

# Testing if the pass has already been scheduled
# Scheduling the upcoming pass using at if no schedule exists yet
times=`atq | grep -o [0-2][0-9]:[0-5][0-9]`

if [[ $evening_rec -eq 0 ]]; then
if [[ $passhour-gt> 15 ]]; then
at -Mf ~/AutoLRPT/scheduler $passhour:$passmin
fi
fi

if [[ $times != *$passhour:$passmin* ]]; then
  at -Mf ~/AutoLRPT/start-mlrpt $passhour:$passmin
fi
