#!/bin/bash

# Get time of the upcoming pass from predict
passtime=`predict '-p' METEOR-M2 | grep -o -m1 [0-2][0-9]:[0-5][0-9]`

passhour=`cut -c 1-2 <<< $passtime`
passmin=`cut -c 4-5 <<< $passtime`

# Convert from UTC to local time
tzoffset=`date +%z | cut -c 1-3`

passhour=$(($passhour + $tzoffset))


# Testing if pass has already been scheduled
# Scheduling the upcoming pass using at if no schedule exists yet
times=`atq | grep -o [0-2][0-9]:[0-5][0-9]`


if [[ $times != *$passhour:$passmin* ]]; then
  at -Mf ~/AutoLRPT/start-mlrpt $passhour:$passmin
fi
