#!/bin/bash

# This bash script controls the reception itself,
# whereas the script scheduler only schedules the pass time.
# The combination of both scripts works like an infinite loop,
# that always starts the other program after the recent one has finished.

# Programs to be closed before mlrpt is being started
# Only one program can access an SDR at a time and, thus,
# mlrpt will crash immediately if another SDR-related program is already running.
# You can add more programs if you want to (Pattern: killall <program>)
killall gqrx

# Idle to make sure that all other SDR-programs are closed
sleep 5s

# Rotate images received in the evening
# Whereas Meteor-M2 is passing from North to South in the morning,
# it passes over from South to North in the evenings.
# Because of that, the images received in the evening are upside down
# by default, but this if-statement rotates them automatically.
# If you don't like this feature you can remove -i

if [ $(date +"%H") -gt 15 ]; then
mlrpt -i

else
mlrpt

fi

sleep 20m
bash ~/AutoLRPT/scheduler
