#!/bin/bash

######################################################################
#                                                                    #
# This script updates the TLE data for Meteor-M2 3 and Meteor-M2 4   #
# and writes it into the file ~/.predict/predict.tle                 #
#                                                                    #
# The sources of the TLE data is Celestrak:                          #
# https://celestrak.org/NORAD/elements/gp.php?CATNR=57166&FORMAT=tle #
# https://celestrak.org/NORAD/elements/gp.php?CATNR=59051&FORMAT=tle #
#                                                                    #
######################################################################


### CONFIG PART ###

## Automatical update of TLE data ##
#  The TLE data of the satellite might change over time,
#  so you can choose whether this script should should
#  update the TLE data in regular intervals of 24 hours

#  Possible values:
#  - 0 : No automatical update (just update once)
#  - 1 : Automatical update every 24 hours
autoupd=0



### OPERATIONAL PART ###

echo "Warning: All the existing TLE data in the file ~/.predict/predict.tle will be overwritten !"
echo "Press Enter to continue or Ctrl + C to exit"
read answer

while true; do
	echo -n > ~/.predict/predict.tle

    tle=`curl https://celestrak.org/NORAD/elements/gp.php?CATNR=57166&FORMAT=tle`
    echo "$tle" >> ~/.predict/predict.tle
	
    tle=`curl https://celestrak.org/NORAD/elements/gp.php?CATNR=59051&FORMAT=tle`
    echo "$tle" >> ~/.predict/predict.tle


	dos2unix ~/.predict/predict.tle

    if [[ $autoupd -eq 1 ]]; then
        sleep 24h
    else
        break
    fi

done
